package com.cihon.changan.common.dao;

import com.cihon.changan.common.model.vo.AccountInf;
import com.cihon.changan.common.model.vo.AccountInfExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AccountInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_inf
     *
     * @mbg.generated Sat Jun 08 10:40:50 CST 2019
     */
    long countByExample(AccountInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_inf
     *
     * @mbg.generated Sat Jun 08 10:40:50 CST 2019
     */
    int deleteByExample(AccountInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_inf
     *
     * @mbg.generated Sat Jun 08 10:40:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_inf
     *
     * @mbg.generated Sat Jun 08 10:40:50 CST 2019
     */
    int insert(AccountInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_inf
     *
     * @mbg.generated Sat Jun 08 10:40:50 CST 2019
     */
    int insertSelective(AccountInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_inf
     *
     * @mbg.generated Sat Jun 08 10:40:50 CST 2019
     */
    List<AccountInf> selectByExample(AccountInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_inf
     *
     * @mbg.generated Sat Jun 08 10:40:50 CST 2019
     */
    AccountInf selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_inf
     *
     * @mbg.generated Sat Jun 08 10:40:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") AccountInf record, @Param("example") AccountInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_inf
     *
     * @mbg.generated Sat Jun 08 10:40:50 CST 2019
     */
    int updateByExample(@Param("record") AccountInf record, @Param("example") AccountInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_inf
     *
     * @mbg.generated Sat Jun 08 10:40:50 CST 2019
     */
    int updateByPrimaryKeySelective(AccountInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_inf
     *
     * @mbg.generated Sat Jun 08 10:40:50 CST 2019
     */
    int updateByPrimaryKey(AccountInf record);
}