package com.cihon.changan.common.dao;

import com.cihon.changan.common.model.vo.CommodityTypes;
import com.cihon.changan.common.model.vo.CommodityTypesExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CommodityTypesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_types
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    long countByExample(CommodityTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_types
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    int deleteByExample(CommodityTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_types
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    int deleteByPrimaryKey(Integer commoditId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_types
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    int insert(CommodityTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_types
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    int insertSelective(CommodityTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_types
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    List<CommodityTypes> selectByExampleWithBLOBs(CommodityTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_types
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    List<CommodityTypes> selectByExample(CommodityTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_types
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    CommodityTypes selectByPrimaryKey(Integer commoditId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_types
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") CommodityTypes record, @Param("example") CommodityTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_types
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") CommodityTypes record, @Param("example") CommodityTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_types
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    int updateByExample(@Param("record") CommodityTypes record, @Param("example") CommodityTypesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_types
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    int updateByPrimaryKeySelective(CommodityTypes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commodity_types
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CommodityTypes record);
}