package com.cihon.changan.common.dao;

import com.cihon.changan.common.model.vo.OrderDetails;
import com.cihon.changan.common.model.vo.OrderDetailsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    long countByExample(OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    int deleteByExample(OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    int deleteByPrimaryKey(Integer orderNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    int insert(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    int insertSelective(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    List<OrderDetails> selectByExample(OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    OrderDetails selectByPrimaryKey(Integer orderNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrderDetails record, @Param("example") OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    int updateByExample(@Param("record") OrderDetails record, @Param("example") OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    int updateByPrimaryKeySelective(OrderDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    int updateByPrimaryKey(OrderDetails record);
}