package com.cihon.changan.common.dao;

import com.cihon.changan.common.model.vo.Statistics;
import com.cihon.changan.common.model.vo.StatisticsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATISTICS
     *
     * @mbg.generated Sun Jun 02 12:08:43 CST 2019
     */
    long countByExample(StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATISTICS
     *
     * @mbg.generated Sun Jun 02 12:08:43 CST 2019
     */
    int deleteByExample(StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATISTICS
     *
     * @mbg.generated Sun Jun 02 12:08:43 CST 2019
     */
    int insert(Statistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATISTICS
     *
     * @mbg.generated Sun Jun 02 12:08:43 CST 2019
     */
    int insertSelective(Statistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATISTICS
     *
     * @mbg.generated Sun Jun 02 12:08:43 CST 2019
     */
    List<Statistics> selectByExampleWithBLOBs(StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATISTICS
     *
     * @mbg.generated Sun Jun 02 12:08:43 CST 2019
     */
    List<Statistics> selectByExample(StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATISTICS
     *
     * @mbg.generated Sun Jun 02 12:08:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") Statistics record, @Param("example") StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATISTICS
     *
     * @mbg.generated Sun Jun 02 12:08:43 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Statistics record, @Param("example") StatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STATISTICS
     *
     * @mbg.generated Sun Jun 02 12:08:43 CST 2019
     */
    int updateByExample(@Param("record") Statistics record, @Param("example") StatisticsExample example);
}