package com.cihon.changan.common.dao;

import com.cihon.changan.common.model.vo.TStatistics;
import com.cihon.changan.common.model.vo.TStatisticsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    long countByExample(TStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    int deleteByExample(TStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    int insert(TStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    int insertSelective(TStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    List<TStatistics> selectByExample(TStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    TStatistics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    int updateByExampleSelective(@Param("record") TStatistics record, @Param("example") TStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    int updateByExample(@Param("record") TStatistics record, @Param("example") TStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    int updateByPrimaryKeySelective(TStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_statistics
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    int updateByPrimaryKey(TStatistics record);
}