package com.cihon.changan.common.model.vo;

public class AccountInf {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_inf.id
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_inf.tel
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    private Integer tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_inf.Superior
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    private String superior;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_inf.level
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_inf.id
     *
     * @return the value of account_inf.id
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_inf.id
     *
     * @param id the value for account_inf.id
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_inf.tel
     *
     * @return the value of account_inf.tel
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public Integer getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_inf.tel
     *
     * @param tel the value for account_inf.tel
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public void setTel(Integer tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_inf.Superior
     *
     * @return the value of account_inf.Superior
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public String getSuperior() {
        return superior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_inf.Superior
     *
     * @param superior the value for account_inf.Superior
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public void setSuperior(String superior) {
        this.superior = superior == null ? null : superior.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_inf.level
     *
     * @return the value of account_inf.level
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_inf.level
     *
     * @param level the value for account_inf.level
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }
}