package com.cihon.changan.common.model.vo;

public class Administrator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.id
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.user_name
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.user_pwd
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    private String userPwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.id
     *
     * @return the value of administrator.id
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.id
     *
     * @param id the value for administrator.id
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.user_name
     *
     * @return the value of administrator.user_name
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.user_name
     *
     * @param userName the value for administrator.user_name
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.user_pwd
     *
     * @return the value of administrator.user_pwd
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.user_pwd
     *
     * @param userPwd the value for administrator.user_pwd
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }
}