package com.cihon.changan.common.model.vo;

public class CommodityTypes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_types.commodit_id
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    private Integer commoditId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_types.Trade_name
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    private String tradeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity_types.type
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_types.commodit_id
     *
     * @return the value of commodity_types.commodit_id
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public Integer getCommoditId() {
        return commoditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_types.commodit_id
     *
     * @param commoditId the value for commodity_types.commodit_id
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public void setCommoditId(Integer commoditId) {
        this.commoditId = commoditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_types.Trade_name
     *
     * @return the value of commodity_types.Trade_name
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public String getTradeName() {
        return tradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_types.Trade_name
     *
     * @param tradeName the value for commodity_types.Trade_name
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public void setTradeName(String tradeName) {
        this.tradeName = tradeName == null ? null : tradeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity_types.type
     *
     * @return the value of commodity_types.type
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity_types.type
     *
     * @param type the value for commodity_types.type
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}