package com.cihon.changan.common.model.vo;

public class OrderDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.order_number
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    private Integer orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.commodit_id
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    private Integer commoditId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.number
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.id
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.order_number
     *
     * @return the value of order_details.order_number
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public Integer getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.order_number
     *
     * @param orderNumber the value for order_details.order_number
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.commodit_id
     *
     * @return the value of order_details.commodit_id
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public Integer getCommoditId() {
        return commoditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.commodit_id
     *
     * @param commoditId the value for order_details.commodit_id
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public void setCommoditId(Integer commoditId) {
        this.commoditId = commoditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.number
     *
     * @return the value of order_details.number
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.number
     *
     * @param number the value for order_details.number
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.id
     *
     * @return the value of order_details.id
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.id
     *
     * @param id the value for order_details.id
     *
     * @mbg.generated Sat Jun 01 14:15:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }
}