package com.cihon.changan.common.model.vo;

public class TStatistics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.id
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.one
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    private Integer one;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.two
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    private Integer two;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.three
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    private Integer three;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.one_order
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    private Integer oneOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.two_order
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    private Integer twoOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.three_order
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    private Integer threeOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_statistics.a_id
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    private Integer aId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.id
     *
     * @return the value of t_statistics.id
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.id
     *
     * @param id the value for t_statistics.id
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.one
     *
     * @return the value of t_statistics.one
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    public Integer getOne() {
        return one;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.one
     *
     * @param one the value for t_statistics.one
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    public void setOne(Integer one) {
        this.one = one;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.two
     *
     * @return the value of t_statistics.two
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    public Integer getTwo() {
        return two;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.two
     *
     * @param two the value for t_statistics.two
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    public void setTwo(Integer two) {
        this.two = two;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.three
     *
     * @return the value of t_statistics.three
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    public Integer getThree() {
        return three;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.three
     *
     * @param three the value for t_statistics.three
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    public void setThree(Integer three) {
        this.three = three;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.one_order
     *
     * @return the value of t_statistics.one_order
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    public Integer getOneOrder() {
        return oneOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.one_order
     *
     * @param oneOrder the value for t_statistics.one_order
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    public void setOneOrder(Integer oneOrder) {
        this.oneOrder = oneOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.two_order
     *
     * @return the value of t_statistics.two_order
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    public Integer getTwoOrder() {
        return twoOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.two_order
     *
     * @param twoOrder the value for t_statistics.two_order
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    public void setTwoOrder(Integer twoOrder) {
        this.twoOrder = twoOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.three_order
     *
     * @return the value of t_statistics.three_order
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    public Integer getThreeOrder() {
        return threeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.three_order
     *
     * @param threeOrder the value for t_statistics.three_order
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    public void setThreeOrder(Integer threeOrder) {
        this.threeOrder = threeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_statistics.a_id
     *
     * @return the value of t_statistics.a_id
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_statistics.a_id
     *
     * @param aId the value for t_statistics.a_id
     *
     * @mbg.generated Sat Jun 08 11:59:09 CST 2019
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }
}