spring:
  application:
    name: changan-project
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://169.254.28.135/back?useUnicode=true&characterEncoding=utf8
    username: root
    password: dljyxx225
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enabled: false

  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates
    suffix: .html
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**


mybatis:
  mapper-locations: classpath*:com/cihon/changan/**/dao/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8010
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/
logging:
  level:
    com.cihon.changan.project.dao: DEBUG
#thymelea模板配置
